//
// Generated file, do not edit! Created by nedtool 5.4 from node/sensorManager/SensorManagerMessage.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __SENSORMANAGERMESSAGE_M_H
#define __SENSORMANAGERMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>node/sensorManager/SensorManagerMessage.msg:13</tt> by nedtool.
 * <pre>
 * message SensorReadingMessage
 * {
 *     double sensedValue;
 *     string sensorType;
 *     int sensorIndex;
 * }
 * </pre>
 */
class SensorReadingMessage : public ::omnetpp::cMessage
{
  protected:
    double sensedValue;
    ::omnetpp::opp_string sensorType;
    int sensorIndex;

  private:
    void copy(const SensorReadingMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SensorReadingMessage&);

  public:
    SensorReadingMessage(const char *name=nullptr, short kind=0);
    SensorReadingMessage(const SensorReadingMessage& other);
    virtual ~SensorReadingMessage();
    SensorReadingMessage& operator=(const SensorReadingMessage& other);
    virtual SensorReadingMessage *dup() const override {return new SensorReadingMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getSensedValue() const;
    virtual void setSensedValue(double sensedValue);
    virtual const char * getSensorType() const;
    virtual void setSensorType(const char * sensorType);
    virtual int getSensorIndex() const;
    virtual void setSensorIndex(int sensorIndex);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SensorReadingMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SensorReadingMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SENSORMANAGERMESSAGE_M_H

