//
// Generated file, do not edit! Created by nedtool 5.4 from node/application/roomMonitoring/RoomMonitoringPacket.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __ROOMMONITORINGPACKET_M_H
#define __ROOMMONITORINGPACKET_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "ApplicationPacket_m.h"
// }}

/**
 * Class generated from <tt>node/application/roomMonitoring/RoomMonitoringPacket.msg:19</tt> by nedtool.
 * <pre>
 * packet RoomMonitoringDataPacket extends ApplicationPacket
 * {
 *     int sourceNodeID;	//the ID of the source node
 * }
 * </pre>
 */
class RoomMonitoringDataPacket : public ::ApplicationPacket
{
  protected:
    int sourceNodeID;

  private:
    void copy(const RoomMonitoringDataPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RoomMonitoringDataPacket&);

  public:
    RoomMonitoringDataPacket(const char *name=nullptr, short kind=0);
    RoomMonitoringDataPacket(const RoomMonitoringDataPacket& other);
    virtual ~RoomMonitoringDataPacket();
    RoomMonitoringDataPacket& operator=(const RoomMonitoringDataPacket& other);
    virtual RoomMonitoringDataPacket *dup() const override {return new RoomMonitoringDataPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSourceNodeID() const;
    virtual void setSourceNodeID(int sourceNodeID);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RoomMonitoringDataPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RoomMonitoringDataPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ROOMMONITORINGPACKET_M_H

