//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/application/roomMonitoring/RoomMonitoringPacket.msg.
//

#ifndef _ROOMMONITORINGPACKET_M_H_
#define _ROOMMONITORINGPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "ApplicationPacket_m.h"
// }}

/**
 * Class generated from <tt>src/node/application/roomMonitoring/RoomMonitoringPacket.msg:19</tt> by nedtool.
 * <pre>
 * packet RoomMonitoringDataPacket extends ApplicationPacket
 * {
 *     int sourceNodeID;	//the ID of the source node
 * }
 * </pre>
 */
class RoomMonitoringDataPacket : public ::ApplicationPacket
{
  protected:
    int sourceNodeID_var;

  private:
    void copy(const RoomMonitoringDataPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RoomMonitoringDataPacket&);

  public:
    RoomMonitoringDataPacket(const char *name=NULL, int kind=0);
    RoomMonitoringDataPacket(const RoomMonitoringDataPacket& other);
    virtual ~RoomMonitoringDataPacket();
    RoomMonitoringDataPacket& operator=(const RoomMonitoringDataPacket& other);
    virtual RoomMonitoringDataPacket *dup() const {return new RoomMonitoringDataPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSourceNodeID() const;
    virtual void setSourceNodeID(int sourceNodeID);
};

inline void doPacking(cCommBuffer *b, RoomMonitoringDataPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RoomMonitoringDataPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _ROOMMONITORINGPACKET_M_H_

