//
// Generated file, do not edit! Created by nedtool 5.4 from node/communication/routing/aodvRouting/AodvRoutingDataPacket.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __AODVROUTINGDATAPACKET_M_H
#define __AODVROUTINGDATAPACKET_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "PacketId_m.h"
// }}

/**
 * Class generated from <tt>node/communication/routing/aodvRouting/AodvRoutingDataPacket.msg:21</tt> by nedtool.
 * <pre>
 * packet AodvDataPacket extends PacketId
 * {
 *     string destinationAodv;
 * }
 * </pre>
 */
class AodvDataPacket : public ::PacketId
{
  protected:
    ::omnetpp::opp_string destinationAodv;

  private:
    void copy(const AodvDataPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AodvDataPacket&);

  public:
    AodvDataPacket(const char *name=nullptr, short kind=0);
    AodvDataPacket(const AodvDataPacket& other);
    virtual ~AodvDataPacket();
    AodvDataPacket& operator=(const AodvDataPacket& other);
    virtual AodvDataPacket *dup() const override {return new AodvDataPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDestinationAodv() const;
    virtual void setDestinationAodv(const char * destinationAodv);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AodvDataPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AodvDataPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __AODVROUTINGDATAPACKET_M_H

