//
// Generated file, do not edit! Created by nedtool 5.4 from node/communication/routing/aodvRouting/PacketId.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __PACKETID_M_H
#define __PACKETID_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "RoutingPacket_m.h"
// }}

/**
 * Class generated from <tt>node/communication/routing/aodvRouting/PacketId.msg:7</tt> by nedtool.
 * <pre>
 * packet PacketId extends RoutingPacket
 * {
 *     unsigned int id;
 * }
 * </pre>
 */
class PacketId : public ::RoutingPacket
{
  protected:
    unsigned int id;

  private:
    void copy(const PacketId& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PacketId&);

  public:
    PacketId(const char *name=nullptr, short kind=0);
    PacketId(const PacketId& other);
    virtual ~PacketId();
    PacketId& operator=(const PacketId& other);
    virtual PacketId *dup() const override {return new PacketId(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getId() const;
    virtual void setId(unsigned int id);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PacketId& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PacketId& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PACKETID_M_H

