//
// Generated file, do not edit! Created by nedtool 5.4 from node/resourceManager/ResourceManagerMessage.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __RESOURCEMANAGERMESSAGE_M_H
#define __RESOURCEMANAGERMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>node/resourceManager/ResourceManagerMessage.msg:13</tt> by nedtool.
 * <pre>
 * message ResourceManagerMessage
 * {
 *     double powerConsumed;
 * }
 * </pre>
 */
class ResourceManagerMessage : public ::omnetpp::cMessage
{
  protected:
    double powerConsumed;

  private:
    void copy(const ResourceManagerMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ResourceManagerMessage&);

  public:
    ResourceManagerMessage(const char *name=nullptr, short kind=0);
    ResourceManagerMessage(const ResourceManagerMessage& other);
    virtual ~ResourceManagerMessage();
    ResourceManagerMessage& operator=(const ResourceManagerMessage& other);
    virtual ResourceManagerMessage *dup() const override {return new ResourceManagerMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getPowerConsumed() const;
    virtual void setPowerConsumed(double powerConsumed);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ResourceManagerMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ResourceManagerMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __RESOURCEMANAGERMESSAGE_M_H

