//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/application/distanceTest/DistanceTestPacket.msg.
//

#ifndef _DISTANCETESTPACKET_M_H_
#define _DISTANCETESTPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "ApplicationPacket_m.h"
// }}

/**
 * Struct generated from src/node/application/distanceTest/DistanceTestPacket.msg:19 by nedtool.
 */
struct DistanceReportData
{
    DistanceReportData();
    unsigned short nodeID;
    double locX;
    double locY;
};

void doPacking(cCommBuffer *b, DistanceReportData& a);
void doUnpacking(cCommBuffer *b, DistanceReportData& a);

/**
 * Class generated from <tt>src/node/application/distanceTest/DistanceTestPacket.msg:25</tt> by nedtool.
 * <pre>
 * packet DistanceTestDataPacket extends ApplicationPacket
 * {
 *     DistanceReportData extraData;
 * }
 * </pre>
 */
class DistanceTestDataPacket : public ::ApplicationPacket
{
  protected:
    DistanceReportData extraData_var;

  private:
    void copy(const DistanceTestDataPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DistanceTestDataPacket&);

  public:
    DistanceTestDataPacket(const char *name=NULL, int kind=0);
    DistanceTestDataPacket(const DistanceTestDataPacket& other);
    virtual ~DistanceTestDataPacket();
    DistanceTestDataPacket& operator=(const DistanceTestDataPacket& other);
    virtual DistanceTestDataPacket *dup() const {return new DistanceTestDataPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual DistanceReportData& getExtraData();
    virtual const DistanceReportData& getExtraData() const {return const_cast<DistanceTestDataPacket*>(this)->getExtraData();}
    virtual void setExtraData(const DistanceReportData& extraData);
};

inline void doPacking(cCommBuffer *b, DistanceTestDataPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DistanceTestDataPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _DISTANCETESTPACKET_M_H_

