//
// Generated file, do not edit! Created by nedtool 4.6 from src/actions/destroy/DestroyRequest.msg.
//

#ifndef _DESTROYREQUEST_M_H_
#define _DESTROYREQUEST_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "EntryWrapper.h"
// }}

/**
 * Class generated from <tt>src/actions/destroy/DestroyRequest.msg:15</tt> by nedtool.
 * <pre>
 * message DestroyRequest
 * {
 *     EntryWrapper entryWrapper;
 * 
 * }
 * </pre>
 */
class DestroyRequest : public ::cMessage
{
  protected:
    EntryWrapper entryWrapper_var;

  private:
    void copy(const DestroyRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DestroyRequest&);

  public:
    DestroyRequest(const char *name=NULL, int kind=0);
    DestroyRequest(const DestroyRequest& other);
    virtual ~DestroyRequest();
    DestroyRequest& operator=(const DestroyRequest& other);
    virtual DestroyRequest *dup() const {return new DestroyRequest(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual EntryWrapper& getEntryWrapper();
    virtual const EntryWrapper& getEntryWrapper() const {return const_cast<DestroyRequest*>(this)->getEntryWrapper();}
    virtual void setEntryWrapper(const EntryWrapper& entryWrapper);
};

inline void doPacking(cCommBuffer *b, DestroyRequest& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DestroyRequest& obj) {obj.parsimUnpack(b);}


#endif // ifndef _DESTROYREQUEST_M_H_

