//
// Generated file, do not edit! Created by nedtool 5.4 from node/mobilityManager/MobilityManagerMessage.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __MOBILITYMANAGERMESSAGE_M_H
#define __MOBILITYMANAGERMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>node/mobilityManager/MobilityManagerMessage.msg:13</tt> by nedtool.
 * <pre>
 * enum MobilityManagerMessageType
 * {
 *     MOBILITY_PERIODIC = 1;
 * }
 * </pre>
 */
enum MobilityManagerMessageType {
    MOBILITY_PERIODIC = 1
};

/**
 * Class generated from <tt>node/mobilityManager/MobilityManagerMessage.msg:17</tt> by nedtool.
 * <pre>
 * message MobilityManagerMessage
 * {
 * }
 * </pre>
 */
class MobilityManagerMessage : public ::omnetpp::cMessage
{
  protected:

  private:
    void copy(const MobilityManagerMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MobilityManagerMessage&);

  public:
    MobilityManagerMessage(const char *name=nullptr, short kind=0);
    MobilityManagerMessage(const MobilityManagerMessage& other);
    virtual ~MobilityManagerMessage();
    MobilityManagerMessage& operator=(const MobilityManagerMessage& other);
    virtual MobilityManagerMessage *dup() const override {return new MobilityManagerMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MobilityManagerMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MobilityManagerMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __MOBILITYMANAGERMESSAGE_M_H

